-- Confessions Table
create table if not exists confessions (
    id bigint generated by default as identity primary key,
    content text not null,
    media_url text,
    likes integer default 0,
    created_at timestamp with time zone default now()
);

-- Comments Table
create table if not exists comments (
    id bigint generated by default as identity primary key,
    post_id bigint references confessions(id) on delete cascade,
    text text not null,
    created_at timestamp with time zone default now()
);

-- Optional: Emoji Reactions
create table if not exists reactions (
    id bigint generated by default as identity primary key,
    post_id bigint references confessions(id) on delete cascade,
    emoji text,
    created_at timestamp with time zone default now()
);

-- Storage Bucket for uploads
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do nothing;
