-- confessions
create table if not exists public.confessions (
    id bigint generated by default as identity primary key,
    text text,
    media_url text,
    media_type text,
    tags text[],
    likes_count bigint default 0,
    reported boolean default false,
    approved boolean default false,
    views bigint default 0,
    created_at timestamp with time zone default now()
);

-- comments
create table if not exists public.comments (
    id bigint generated by default as identity primary key,
    post_id bigint references public.confessions(id) on delete cascade,
    text text not null,
    created_at timestamp with time zone default now()
);

-- reactions
create table if not exists public.reactions (
    id bigint generated by default as identity primary key,
    post_id bigint references public.confessions(id) on delete cascade,
    emoji text not null,
    count int default 0
);

-- actions log (for rate-limiting/auditing)
create table if not exists public.actions_log (
    id bigint generated by default as identity primary key,
    ip text,
    action text,
    created_at timestamp with time zone default now()
);

-- make storage bucket using Supabase UI (uploads/confessions)
-- For dev convenience (do this in dashboard): create bucket named 'confessions'
